apiVersion: v1
kind: Pod
metadata:
  name: eureka-pod
  labels:
    app: eureka
spec:
  containers:
  - name: eureka-container
    image: rahulnehra477/eureka_server:v1
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
